---
- hosts: all

  vars:
    mysql_root_home: /root
    mysql_root_username: 'root'
    mysql_root_password: 'root'
    #mysql_root_password: ^superSecurePassword123$

    drupal_db:
      user: drupal
      password: "wo#24n$fTD&CqNSqD6"
      name: drupal

    mysql_users:
      - name: "{{ drupal_db.user }}"
        host: "%"
        password: "{{ drupal_db.password }}"
        priv: "{{ drupal_db.name }}.*:ALL"

    mysql_databases:
      - name: "{{ drupal_db.name }}"
        encoding: utf8mb4
        collation: utf8mb4_general_ci

  tasks:
      # PHP 7 stuff
    - name: PHP | Add php-7.0 PPA
      apt_repository: repo='ppa:ondrej/php'
                  state=present
                  update_cache=yes

    - name: PHP | install php packages
      apt: pkg={{ item }} state=installed
      with_items:
        - php7.0-fpm
        - php7.0-cli
        - php7.0-common
        - php7.0-curl
        - php7.0-json
        - php7.0-gd
        - php7.0-mcrypt
        - php7.0-odbc
        - php7.0-mbstring
        - php7.0-mysql
        - php7.0-xmlrpc
        - php7.0-opcache
        - php7.0-intl
        - php7.0-bz2
        - php7.0-xml

    - name: MySQL | Install MySQL
      apt: pkg={{ item }} state=installed
      with_items:
        - mysql-common
        - mysql-server
        - python3-mysqldb

    - name: Copy .my.cnf file with root password credentials.
      template:
        src: templates/root-my.cnf.j2
        dest: "{{ mysql_root_home }}/.my.cnf"
        owner: root
        group: root
        mode: 0600

    - name: Disallow root login remotely
      command: 'mysql -NBe "{{ item }}"'
      with_items:
        - DELETE FROM mysql.user WHERE User='{{ mysql_root_username }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')

    - name: Get list of hosts for the root user.
      command: mysql -NBe "SELECT Host FROM mysql.user WHERE User = '{{ mysql_root_username }}' ORDER BY (Host='localhost') ASC"
      register: mysql_root_hosts

    - name: Update MySQL root password for localhost root account (5.7.x).
      shell: >
        mysql -u root -NBe
        'ALTER USER "{{ mysql_root_username }}"@"{{ item }}" IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";'
      with_items: "{{ mysql_root_hosts.stdout_lines|default([]) }}"

    - name: MySQL | Ensure MySQL users are present.
      mysql_user:
        name: "{{ item.name }}"
        host: "{{ item.host | default('localhost') }}"
        password: "{{ item.password }}"
        priv: "{{ item.priv | default('*.*:USAGE') }}"
        state: "{{ item.state | default('present') }}"
        append_privs: "{{ item.append_privs | default('no') }}"
      with_items: "{{ mysql_users }}"


    - name: MySQL | Ensure MySQL databases are present.
      mysql_db:
        name: "{{ item.name }}"
        collation: "{{ item.collation | default('utf8_general_ci') }}"
        encoding: "{{ item.encoding | default('utf8') }}"
        state: present
      with_items: "{{ mysql_databases }}"
