---
- hosts: all
  gather_facts: False
  
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=86400
    - name: PHP | Add php-7.0 PPA
      apt_repository: repo='ppa:ondrej/php'
                  state=present
                  update_cache=yes
      sudo: true